CLOBBER
MONITOR 1
GETXS 1 1102
GETDECAY 1
FISPACT
* 10 MIN 10 MeV Os
PRINTLIB 2
MASS 1.0 1
Os 100
MIND 1E2
UNCERTAINTY 2
HALF
HAZARDS
<< -- irrad -- >>
FLUX 1E12
ATOMS 
TIME 10 MINS
ATOMS 
<< -- cool -- >>
FLUX 0.0
ZERO
TIME 1 MINS ATOMS 
TIME 1 MINS ATOMS 
TIME 1 MINS ATOMS 
TIME 1 MINS ATOMS 
TIME 1 MINS ATOMS 
TIME 1 MINS ATOMS 
TIME 1 MINS ATOMS 
TIME 1 MINS ATOMS 
TIME 1 MINS ATOMS 
TIME 1 MINS ATOMS 
TIME 1 MINS ATOMS 
TIME 1 MINS ATOMS 
TIME 1 MINS ATOMS 
TIME 1 MINS ATOMS 
TIME 1 MINS ATOMS 
TIME 1 MINS ATOMS 
TIME 1 MINS ATOMS 
TIME 1 MINS ATOMS 
TIME 1 MINS ATOMS 
TIME 1 MINS ATOMS 
TIME 1 MINS ATOMS 
TIME 1 MINS ATOMS 
TIME 1 MINS ATOMS 
TIME 1 MINS ATOMS 
TIME 1 MINS ATOMS 
TIME 1 MINS ATOMS 
TIME 1 MINS ATOMS 
TIME 1 MINS ATOMS 
TIME 1 MINS ATOMS 
TIME 1 MINS ATOMS 
TIME 1 MINS ATOMS 
TIME 1 MINS ATOMS 
TIME 1 MINS ATOMS 
TIME 1 MINS ATOMS 
TIME 1 MINS ATOMS 
TIME 1 MINS ATOMS 
TIME 1 MINS ATOMS 
TIME 1 MINS ATOMS 
TIME 1 MINS ATOMS 
TIME 1 MINS ATOMS 
TIME 1 MINS ATOMS 
TIME 1 MINS ATOMS 
TIME 1 MINS ATOMS 
TIME 1 MINS ATOMS 
TIME 1 MINS ATOMS 
TIME 1 MINS ATOMS 
TIME 1 MINS ATOMS 
TIME 1 MINS ATOMS 
TIME 1 MINS ATOMS 
TIME 1 MINS ATOMS 
TIME 1 MINS ATOMS 
TIME 1 MINS ATOMS 
TIME 1 MINS ATOMS 
TIME 1 MINS ATOMS 
TIME 1 MINS ATOMS 
TIME 1 MINS ATOMS 
TIME 1 MINS ATOMS 
TIME 1 MINS ATOMS 
TIME 1 MINS ATOMS 
TIME 1 MINS ATOMS
END 
* END 
/*